export type Exercise = {
  id: string;
  name: string;
  pf: string;
  sets: number;
  reps: string;
  rir?: string;
  videoUrl?: string;
  rest: string;
  restS: number;
  hint: string;
  repField?: "sec";
  note?: string;
};

export type Day = "A" | "B" | "C" | "D";
export type Mode = "std" | "pf";

export type Workout = {
  title: string;
  focus: string;
  warm: string;
  ex: Exercise[];
};

export const DAYS: Day[] = ["A", "B", "C", "D"];

export const PLAN: Record<Day, Workout> = {
  A: {
    title: "Workout A",
    focus: "Chest & Tricep",
    warm: "Warm up first: 5 min light cardio + 1–2 light sets of your first exercise.",
    ex: [
      {
        id: "a_bench",
        name: "Bench Press",
        pf: "Chest Press machine or Smith-machine bench",
        sets: 3,
        reps: "8 or 10",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/D8hdaIMAAJQ?si=h2E95VWXqjq4e8gR",
        rest: "2–3 min",
        restS: 180,
        hint: "lbs",
      },
      {
        id: "a_incline",
        name: "Incline Chest Press",
        pf: "Incline Chest Press machine or incline dumbbell press",
        sets: 3,
        reps: "8 or 10",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/FYBcBpTVkv0?si=YF9t4e__eD29hG28",
        rest: "2 min",
        restS: 120,
        hint: "lbs",
      },
      {
        id: "a_fly",
        name: "Dumbbell Chest Fly",
        pf: "Pec Deck / Chest Fly machine",
        sets: 3,
        reps: "8 or 10",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/7dOwo7jvIjA?si=Gatc_dEjAuBJiNxh",
        rest: "1.5 min",
        restS: 90,
        hint: "lbs",
      },
      {
        id: "a_tri_push",
        name: "Tricep Rope Pushdown",
        pf: "Cable tricep pushdown — PF has this",
        sets: 3,
        reps: "8 or 10",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/ooDIDaTmp6I?si=a8Kz0gKnhajGnV-y",
        rest: "1.5 min",
        restS: 90,
        hint: "lbs",
      },
      {
        id: "a_tri_oh",
        name: "Tricep Overhead Extension",
        pf: "Cable overhead extension or dumbbell — PF has both",
        sets: 3,
        reps: "8 or 10",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/fahr9ZDvVtY?si=TJoHnuxOrxYx-cbv",
        rest: "1.5 min",
        restS: 90,
        hint: "lbs",
      },
    ],
  },
  B: {
    title: "Workout B",
    focus: "Back & Bicep",
    warm: "Warm up first: 5 min light cardio + 1–2 light sets of your first exercise.",
    ex: [
      {
        id: "b_dl",
        name: "Deadlift",
        pf: "Smith-machine RDL or dumbbell RDL + Seated Leg Curl",
        sets: 3,
        reps: "6 or 8",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/tl2M46FfzEc?si=HP5KP6IY0nW3c3FO",
        rest: "2–3 min",
        restS: 180,
        hint: "lbs",
        note: "PF can't do conventional deadlifts traditionally. Use the Smith machine for Romanian deadlifts, or do dumbbell RDLs, then pair with the Seated Leg Curl machine to cover your hamstrings.",
      },
      {
        id: "b_pullup",
        name: "Pull-ups",
        pf: "Assisted Pull-up/Dip machine or Lat Pulldown",
        sets: 3,
        reps: "Maximum Reps",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/rsTPMUZUjkY?si=ebtE06tS1q1J5YgH",
        rest: "2 min",
        restS: 120,
        hint: "reps",
      },
      {
        id: "b_row",
        name: "Barbell Row",
        pf: "Seated Cable Row machine or Smith-machine row",
        sets: 3,
        reps: "8 or 10",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/W0vv2LtgZ28?si=EsjLiKPRFSKte9qk",
        rest: "2 min",
        restS: 120,
        hint: "lbs",
      },
      {
        id: "b_curl",
        name: "Bicep Curl",
        pf: "Cable curl or dumbbells — PF has both",
        sets: 3,
        reps: "10 or 12",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/1AMMyp28MdQ?si=7XfA8J1G6yCdpXN1",
        rest: "1.5 min",
        restS: 90,
        hint: "lbs",
      },
      {
        id: "b_hammer",
        name: "Hammer Curl",
        pf: "Dumbbells or cable — PF has both",
        sets: 3,
        reps: "12 or 14",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/_Nllgt5LM84?si=zVN3d_bDI_1B1EOF",
        rest: "1.5 min",
        restS: 90,
        hint: "lbs",
      },
    ],
  },
  C: {
    title: "Workout C",
    focus: "Shoulder & Abs",
    warm: "Warm up first: 5 min light cardio + 1–2 light sets of your first exercise.",
    ex: [
      {
        id: "c_ohp",
        name: "Dumbbell Shoulder Press",
        pf: "Shoulder Press machine",
        sets: 3,
        reps: "8 or 10",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/5Ozbt8SdR_A?si=U5kev-dFq3uO87cg",
        rest: "2 min",
        restS: 120,
        hint: "lbs",
      },
      {
        id: "c_lat_raise",
        name: "Dumbbell Lateral Raises",
        pf: "Dumbbells or cable lateral raise — PF has both",
        sets: 3,
        reps: "12 or 14",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/CADKU4SJ624?si=Hq2BS-E2aqv5qEJJ",
        rest: "1.5 min",
        restS: 90,
        hint: "lbs",
      },
      {
        id: "c_front_raise",
        name: "Front Raises",
        pf: "Dumbbells or cable — PF has both",
        sets: 3,
        reps: "12 or 14",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/3nx5_OJs8iY?si=FIAj37iZytgZ8qxO",
        rest: "1.5 min",
        restS: 90,
        hint: "lbs",
      },
      {
        id: "c_twist",
        name: "Russian Twist",
        pf: "Same, just on the floor",
        sets: 3,
        reps: "15 or 20",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/B0k51rUbu_I?si=rT-PcCyPqJDP4btg",
        rest: "1 min",
        restS: 60,
        hint: "reps",
      },
      {
        id: "c_plank",
        name: "Plank",
        pf: "Same, just on the floor",
        sets: 3,
        reps: "30 or 60 sec",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/bgT3JP1lxvk?si=bupDYWJSeX8gW3I_",
        rest: "1 min",
        restS: 60,
        hint: "sec",
        repField: "sec",
      },
    ],
  },
  D: {
    title: "Workout D",
    focus: "Legs",
    warm: "Warm up first: 5 min light cardio + 1–2 light sets of your first exercise.",
    ex: [
      {
        id: "d_squat",
        name: "Full Squat Smith Machine",
        pf: "Smith-machine squat or Leg Press",
        sets: 3,
        reps: "8 or 10",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/HQVh6gZNgyg?si=EFUnj92J2V54JW8h",
        rest: "2–3 min",
        restS: 180,
        hint: "lbs",
      },
      {
        id: "d_lunge",
        name: "Lunges",
        pf: "Dumbbell lunges or Leg Press",
        sets: 3,
        reps: "10 or 12",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/HAVF3m1HOu0?si=EY76c0udpiVKUUwO",
        rest: "1.5 min",
        restS: 90,
        hint: "lbs",
      },
      {
        id: "d_leg_press",
        name: "Leg Press",
        pf: "Leg Press machine — PF has this",
        sets: 3,
        reps: "12 or 14",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/mPKiHEqhQUo?si=QtG7mK7OdaDwl2Y9",
        rest: "2 min",
        restS: 120,
        hint: "lbs",
      },
      {
        id: "d_leg_ext",
        name: "Leg Extension",
        pf: "Leg Extension machine — PF has this",
        sets: 3,
        reps: "15 or 20",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/FHC4uuoro-s?si=UIWpmqr9CZvEETsm",
        rest: "1.5 min",
        restS: 90,
        hint: "lbs",
      },
      {
        id: "d_leg_curl",
        name: "Leg Curl",
        pf: "Seated or lying Leg Curl machine — PF has this",
        sets: 3,
        reps: "15 or 20",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/lGjUukBLE_Q?si=5XqUytsbb5aRjP98",
        rest: "1.5 min",
        restS: 90,
        hint: "lbs",
      },
      {
        id: "d_calf",
        name: "Calf Raises",
        pf: "Standing or seated calf machine — PF has both",
        sets: 3,
        reps: "15 or 20",
        rir: "+2 / 2 / 0",
        videoUrl: "https://youtu.be/b9a64orlqJc?si=AP-uysC1CwYBlRj_",
        rest: "1.5 min",
        restS: 90,
        hint: "lbs",
      },
    ],
  },
};

export const RULES = [
  {
    n: 1,
    title: "Progressive overload",
    body: "Each week, beat last week — one more rep, or a little more weight. Write it down every session. This is what actually builds muscle.",
  },
  {
    n: 2,
    title: "Form before weight",
    body: "A clean rep with less weight beats a sloppy heavy one. If your form breaks down, the set is over — drop the load and keep it strict.",
  },
  {
    n: 3,
    title: "Consistency & recovery",
    body: "Hit your sessions regularly and give muscles ~48h before training them again. Sleep and protein are part of the program, not extras.",
  },
  {
    n: 4,
    title: "RIR (Reps In Reserve)",
    body: "RIR tells you how many reps you could still do at the end of each set. +2 / 2 / 0 means leave 2 reps in the tank on set 1, 2 on set 2, and go close to failure on set 3.",
  },
];
